const { chromium } = require('C:/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.getByText('从好内容，发现下一个好选题').waitFor();
 assert.match(await page.locator('.notice').innerText(),/模拟数据/);
 assert.equal(await page.locator('svg circle').count(),500);
 fs.mkdirSync('test-results',{recursive:true});
 await page.screenshot({path:'test-results/overview.png',fullPage:true});
 await page.locator('[data-view="ranking"]').click();
 await page.locator('#diagnostics-run').click();await page.getByText('去掉单个维度后的高表现组保留率',{exact:true}).waitFor();
 await page.locator('#query').fill('HW-nonexistent');await page.locator('#filter').click();
 await page.getByText('当前范围没有笔记').waitFor();
 await page.locator('#reset-filter').click();await page.locator('tbody tr').first().waitFor();
 await page.locator('[data-weight="popularity"]').fill('0');await page.locator('[data-weight="favorite_value"]').fill('100');await page.locator('[data-weight="comment"]').fill('0');
 await page.locator('[data-weight="velocity"]').fill('0');await page.locator('[data-weight="engagement_rate"]').fill('0');await page.locator('#reweight').click();await page.getByText('收藏价值 100%',{exact:false}).waitFor();
 await page.locator('.note-title').first().click();await page.locator('#detail[open]').waitFor();
 assert.match(await page.locator('#detail').innerText(),/本地规则拆解/);
 assert.match(await page.locator('#detail').innerText(),/ViralScore 贡献拆解/);assert.match(await page.locator('#detail').innerText(),/主要优势/);
 await page.locator('#close-detail').click();
 await page.locator('[data-view="patterns"]').click();assert.equal(await page.locator('.insight-grid article').count(),5);await page.locator('#pattern-category').selectOption({label:'创意餐盘'});await page.waitForFunction(()=>patternResult?.notes.length===198);assert.match(await page.locator('.tip').first().innerText(),/创意餐盘/);
 await page.locator('[data-view="generate"]').click();await page.locator('#product').fill('手作餐盘');await page.locator('#templates').click();await page.getByText('研究主题：手作餐盘').waitFor();assert.equal(await page.locator('.idea').count(),3);
 assert.match(await page.locator('#generator-output').innerText(),/匹配类别：创意餐盘/);
 assert.match(await page.locator('#generator-output').innerText(),/01 选题策略/);
 assert.match(await page.locator('#generator-output').innerText(),/02 标题 A \/ B \/ C/);
 assert.equal(await page.evaluate(()=>generatorResult.assessment.history.length),1);
 assert.ok(await page.evaluate(()=>new Set(generatorResult.assessment.evaluations.map(x=>x.score)).size>1));
 await page.locator('[data-draft="0"]').fill('编辑后的完整正文');await page.locator('[data-generator-step="4"]').click();assert.match(await page.locator('#assessment').innerText(),/原评分与最终稿已失效/);await page.locator('#review-all').click();await page.locator('#optimize-best').waitFor();await page.locator('#optimize-best').click();await page.getByText('优化前后差异（1 轮）').waitFor();
 const exported=page.waitForEvent('download');await page.locator('#generator-export').click();await exported;
 await page.screenshot({path:'test-results/generator.png',fullPage:true});
 await page.locator('[data-generator-step="1"]').click();await page.locator('#product').fill('跑步鞋');await page.locator('#templates').click();await page.getByText('研究主题：跑步鞋').waitFor();assert.equal(await page.locator('.idea').count(),0);
 await page.locator('[data-view="data"]').click();
 await page.locator('#file').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('\ufeff标题,点赞数,正文\n"<script>alert(1)</script>",100,"第一行\n第二行"\n测试二,200,正文')});
 await page.getByText('test.csv',{exact:true}).waitFor();
 await page.locator('#apply-import').click();await page.getByText('从好内容，发现下一个好选题').waitFor();
 assert.equal(await page.locator('tbody tr').count(),2);
 assert.equal(await page.locator('script').count(),4);
 await page.locator('[data-view="data"]').click();await page.locator('#default').click();
 await page.getByText('小红书好物分享500模拟数据.csv',{exact:true}).waitFor();
 await page.locator('[data-view="overview"]').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);
 console.log('Browser tests passed: real data, ranking/filter/weights, detail, patterns, drafts, CSV multiline/XSS, default restore, mobile.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
