let shotState={image:null,name:'',fields:{},original:{},corrected:{},ocr:null,analysis:null,as_of:null,confirmed:false,addedId:null};
const shotLabels={title:'笔记标题',author:'作者（OCR 可能有错字）',content:'可见正文',tags:'可见标签',cover_text:'内容图片中的文字',likes:'点赞数',favorites:'收藏数',comments:'评论数',followers:'作者粉丝数（可选补充）',publish_time:'确认后的发布日期（可选补充）',date_visible:'截图中的日期文字（仅供核对）'};
const shotAreas=['author','title','body','tags','likes','favorites','comments','content_image'];
function correctionTag(k){return shotState.corrected[k]?'<span class="badge corrected">用户已修正</span>':''}
function screenshotView(){return heading('笔记解析与内容鉴赏','分区识别 → 人工核对 → 内容鉴赏 → 数据表现分析')+`
<div class="grid shot-layout"><article class="panel"><h2>01 上传笔记截图</h2><label class="upload"><strong>选择一张 JPG / PNG / WebP 截图</strong><input id="shot-file" type="file" accept="image/jpeg,image/png,image/webp"><span class="sub">最大 10 MB。本机分区 OCR，图片不会发送到模型服务。</span></label><div id="shot-status" role="status"></div>${shotState.image?`<img src="${shotState.image}" alt="待解析的小红书截图" class="shot-preview"><p class="sub">${esc(shotState.name)}</p><button id="shot-recognize" class="primary">分区识别截图</button>`:'<p class="empty">请上传笔记详情页，尽量包含作者、标题、正文、标签和底部互动栏。</p>'}<p class="tip">系统分别识别作者区、标题区、正文区、标签区、点赞区、收藏区、评论区和内容图片区。不同截图版式可能造成区域偏移，请人工核对。</p></article>
<article class="panel"><h2>02 核对与修正</h2><p class="sub">输入框始终可编辑。修改后会标记“用户已修正”，后续只使用当前输入框内容。</p><div class="form-stack">${Object.entries(shotLabels).map(([k,label])=>`<label><span>${label} ${correctionTag(k)}</span>${['content','cover_text','tags'].includes(k)?`<textarea data-shot="${k}">${esc(shotState.fields[k]||'')}</textarea>`:`<input data-shot="${k}" type="${k==='publish_time'?'date':'text'}" value="${esc(shotState.fields[k]??'')}" ${['likes','favorites','comments','followers'].includes(k)?'inputmode="decimal"':''}>`}${shotState.ocr?.evidence[k]?`<small class="sub">${esc(shotState.ocr.evidence[k])}</small>`:''}</label>`).join('')}</div><label class="optional-date">数据统计日 <input id="shot-date" type="date" value="${shotState.as_of||result.as_of}"></label><p class="tip">粉丝数和发布日期是可选补充项。不填写也能完成内容鉴赏和基础数据表现分析；填写后增加账号体量修正与互动速度，形成完整 ViralScore。</p><label><input id="shot-confirm" type="checkbox" ${shotState.confirmed?'checked':''}> 我已对照截图核对当前识别结果</label><div class="ai-actions"><button class="primary" id="shot-appreciate">开始内容鉴赏</button><button id="shot-clear">清空本篇</button></div></article></div>
${shotState.ocr?regionReview():''}<div id="shot-result">${shotState.analysis?analysisResult(shotState.analysis):''}</div>`}
function regionReview(){return `<article class="panel"><div class="panel-head"><div><h2>分区识别检查</h2><p class="sub">以下原文按截图区域分别提取，用于定位 OCR 错误。</p></div><span class="badge gray">8 个区域</span></div><div class="region-grid">${shotAreas.map(k=>{const r=shotState.ocr.regions[k];return `<div class="region-card"><strong>${esc(r.label)}</strong><small>${r.box.join(' · ')}</small><p>${esc(r.text||'未识别到文字')}</p></div>`}).join('')}</div><ul>${shotState.ocr.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></article>`}
function analysisResult(r){return `<article class="panel appreciation"><div class="heading"><div><div class="eyebrow">CONTENT APPRECIATION</div><h2>内容鉴赏评分</h2><div class="stat-value">${r.appreciation.score.toFixed(1)} <small>/ 100</small></div></div><button id="shot-export">导出本篇分析</button></div><p class="sub">${esc(r.appreciation.method)}</p><div class="appraisal-grid">${r.appreciation.items.map(x=>`<div class="appraisal-card"><div class="appraisal-head"><h3>${esc(x.label)}</h3><b>${x.score}</b></div><div class="appraisal-bar"><i style="width:${x.score}%"></i></div><p>识别信号：${esc(x.evidence)}</p><small>${esc(x.suggestion)}</small></div>`).join('')}</div></article><article class="panel performance"><h2>数据表现分析</h2>${r.performance?performanceResult(r.performance):`<p class="empty">还不能计算数据表现评分。请核对并填写${r.performance_missing.map(k=>esc({likes:'点赞数',favorites:'收藏数',comments:'评论数'}[k])).join('、')}；这不影响上方内容鉴赏。</p>`}<div class="ai-actions"><button id="shot-add">${shotState.addedId?'已加入研究库':'一键加入研究库'}</button><button class="primary" id="shot-to-generator">加入研究库并进入选题工作台</button><span class="sub">研究库笔记会参与同品类检索；缺少完整 ViralScore 的笔记不会被误标为爆款证据。</span></div></article>`}
function performanceResult(s){return `<div class="performance-top"><div><div class="stat-value">${s.score==null?'—':s.score.toFixed(2)} <small>/ 100</small></div><span class="badge">${esc(s.display_status||s.status)}</span></div><p>${s.reference_simulated?'参照当前模拟数据集，仅表示在模拟分布中的相对位置。':'参照当前导入样本，其代表性需自行核实。'}</p></div><p>参照 ${s.reference_count} 篇 · 统计日 ${esc(s.as_of)} · ${s.missing.length?'待补充增强维度：'+s.missing.map(k=>esc(labels[k])).join('、'):'完整五维 ViralScore'}</p><div class="table-wrap"><table><thead><tr><th>维度</th><th>原始值</th><th>参照百分位</th><th>实际权重</th><th>贡献</th></tr></thead><tbody>${Object.keys(s.definitions).map(k=>`<tr><td>${esc(labels[k])}</td><td>${fmt(s.note[k])}</td><td>${fmt(s.components[k])}</td><td>${s.weights[k]==null?'未参与':(s.weights[k]*100).toFixed(1)+'%'}</td><td>${fmt(s.parts[k])}</td></tr>`).join('')}</tbody></table></div><p class="sub">${esc(s.method)}</p><h3>可借鉴证据</h3>${s.advice.map(a=>`<div class="feature"><h3>${esc(a.name)}</h3><div class="evidence">${esc(a.evidence)}</div><p>${esc(a.suggestion)}</p></div>`).join('')}`}
function installShotRows(rows){if(!rows.length)return;const fields=['id','title','content','author','publish_time','likes','favorites','comments','followers','tags'];for(const k of fields)if(!dataset.mapping[k])dataset.mapping[k]=k;let sheet=dataset.sheets.find(s=>s.name==='截图研究库');const headers=fields.map(k=>dataset.mapping[k]);if(!sheet){sheet={name:'截图研究库',headers:[...headers],rows:[]};dataset.sheets.push(sheet)}for(const h of headers)if(!sheet.headers.includes(h))sheet.headers.push(h);for(const raw of rows)if(!sheet.rows.some(r=>r[dataset.mapping.id]===raw.id)){const row={};for(const k of fields)row[dataset.mapping[k]]=raw[k]??'';sheet.rows.push(row)}}
function restoreShotLibrary(){try{installShotRows(JSON.parse(localStorage.getItem('xhs-shot-library')||'[]'))}catch(_){localStorage.removeItem('xhs-shot-library')}}
async function addShotToLibrary(openGenerator){if(!shotState.analysis)throw Error('请先完成人工确认和内容鉴赏。');let saved=[];try{saved=JSON.parse(localStorage.getItem('xhs-shot-library')||'[]')}catch(_){}let id=shotState.addedId;if(!id){id='SHOT-'+Date.now();const row={id,...shotState.fields};saved.push(row);localStorage.setItem('xhs-shot-library',JSON.stringify(saved.slice(-200)));installShotRows([row]);if(!selectedSheets.includes('截图研究库'))selectedSheets.push('截图研究库')}const analysis=shotState.analysis;await recalc();shotState.analysis=analysis;shotState.addedId=id;if(openGenerator){sessionStorage.setItem('product',shotState.fields.title||'截图笔记选题');go('generate')}else{render();toast('已加入截图研究库')}}
function bindScreenshot(){const file=$('#shot-file');if(!file)return;file.onchange=async()=>{const f=file.files[0];if(!f)return;try{if(f.size>10000000)throw Error('图片不能超过 10 MB');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('图片读取失败'));reader.readAsDataURL(f)});shotState={image:data,name:f.name,fields:{},original:{},corrected:{},ocr:null,analysis:null,as_of:null,confirmed:false,addedId:null};render()}catch(e){error(e)}};
 const bind=(id,fn)=>{const el=$('#'+id);if(el)el.onclick=()=>withButton(el,fn)};
 bind('shot-recognize',async()=>{const current=shotState;const snapshot=JSON.stringify(current.fields);$('#shot-status').textContent='正在划分 8 个区域并分别识别…';const out=await api('screenshot/recognize',{data:current.image.split(',')[1]});if(current!==shotState||JSON.stringify(current.fields)!==snapshot)return;shotState.ocr=out;shotState.fields={...out.fields};shotState.original={...out.fields};shotState.corrected={};shotState.analysis=null;shotState.confirmed=false;render()});
 document.querySelectorAll('[data-shot]').forEach(el=>el.onchange=()=>{const k=el.dataset.shot;shotState.fields[k]=el.value;shotState.corrected[k]=true;shotState.analysis=null;shotState.confirmed=false;render()});
 $('#shot-date').onchange=()=>{shotState.as_of=$('#shot-date').value;shotState.analysis=null;render()};
 $('#shot-confirm').onchange=()=>shotState.confirmed=$('#shot-confirm').checked;
 bind('shot-appreciate',async()=>{if(!shotState.confirmed)throw Error('请先对照截图核对当前结果并勾选确认。');const current=shotState;const snapshot=JSON.stringify(current.fields);const scoreDate=$('#shot-date').value;if(!scoreDate)throw Error('请填写数据统计日期。');const out=await api('screenshot/appreciate',{fields:{...current.fields},corrections:{...current.corrected},reference_simulated:dataset.simulated,analysis:{sheets:dataset.sheets.filter(s=>selectedSheets.includes(s.name)),mapping:dataset.mapping,filters,as_of:scoreDate,top_pct:result.top_pct}});if(current!==shotState||JSON.stringify(current.fields)!==snapshot)return;shotState.analysis=out;render();$('#shot-result').scrollIntoView({behavior:'smooth'})});
 bind('shot-add',()=>addShotToLibrary(false));bind('shot-to-generator',()=>addShotToLibrary(true));
 bind('shot-clear',()=>{shotState={image:null,name:'',fields:{},original:{},corrected:{},ocr:null,analysis:null,as_of:null,confirmed:false,addedId:null};render()});
 bind('shot-export',()=>download('笔记解析与内容鉴赏.json',JSON.stringify({filename:shotState.name,fields:shotState.fields,corrections:shotState.corrected,regions:shotState.ocr?.regions,analysis:shotState.analysis},null,2)));
}
